"""Journey set pieces and props (truck, road kit, scenery, depot, doorstep, courier, ship, plane,
catapult, reveal room). Unity space; each prop's origin is where it touches the ground unless noted.

Materials: props use procedural PBR looks (pbr.P names) that build_assets bakes into textures; the
big surfaces (road, grass, floors, walls, sea) use tileable texture sets (tex_ names, generated by
make_textures.py) because one baked atlas would be far too blurry at that size. A model never mixes
the two on the same mesh: large surfaces live on the root, baked details on a child.
"""
import math
import random

import bmesh
from mathutils import Matrix

from hwc_lib import (Model, V, bezier, box, cbox, cyl, decal, displace, ellipsoid, empty, extrude_outline,
                     glass, glow, hull, ico, lathe, matte, prism, rod, rotate_about, sphere, sweep, tex, torus)
from pbr import P

RED = "C7362B"
CREAM = "F3E9D2"
INK = "1F2A44"
TEAL = "2F8F8B"
AMBER = "E0A23A"

PAINT_RED, PAINT_CREAM = P("carpaint", RED), P("carpaint", "EFE6D2")
CHROME = P("chrome", "D9DDE2")
BLACK_PLASTIC = P("plastic", "1E1C1D")
RUBBER = P("rubber", "232123")
TIMBER = P("timber", "8F6E4C")
CARDBOARD = P("cardboard", "B98A55")
TAPE = P("plastic", "C9A060")
FOLIAGE = P("foliage", "4B7030")
BARK = P("bark", "5E4532")


def res(obj, r):
    """Bake resolution for this object (default 1024)."""
    obj["bake_res"] = r
    return obj


def slab(x0, x1, z0, z1, y_bottom, fn, nx, nz):
    """Closed slab whose top surface follows y = fn(x, z) (water, terrain). Smooth shaded."""
    bm = bmesh.new()
    top, bot = [], []
    for i in range(nx + 1):
        rt, rb = [], []
        for j in range(nz + 1):
            x = x0 + (x1 - x0) * i / nx
            z = z0 + (z1 - z0) * j / nz
            rt.append(bm.verts.new((x, fn(x, z), z)))
            rb.append(bm.verts.new((x, y_bottom, z)))
        top.append(rt)
        bot.append(rb)
    for i in range(nx):
        for j in range(nz):
            bm.faces.new((top[i][j], top[i + 1][j], top[i + 1][j + 1], top[i][j + 1]))
            bm.faces.new((bot[i][j], bot[i][j + 1], bot[i + 1][j + 1], bot[i + 1][j]))
    for i in range(nx):
        bm.faces.new((top[i][0], bot[i][0], bot[i + 1][0], top[i + 1][0]))
        bm.faces.new((top[i][nz], top[i + 1][nz], bot[i + 1][nz], bot[i][nz]))
    for j in range(nz):
        bm.faces.new((top[0][j], top[0][j + 1], bot[0][j + 1], bot[0][j]))
        bm.faces.new((top[nx][j], bot[nx][j], bot[nx][j + 1], top[nx][j + 1]))
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
    return bm, True


def canopy(m, center, radius, seed, color=None, blobs=11, voxel=0.045, squash=0.8):
    """Leafy crown: overlapping lumpy spheres fused into one mass (leaf detail comes from the bake)."""
    rnd = random.Random(seed)
    parts = []
    c = V(center)
    mat = color or FOLIAGE
    for k in range(blobs):
        d = V(rnd.uniform(-1, 1), rnd.uniform(-0.6, 0.8) * squash, rnd.uniform(-0.8, 0.8))
        if d.length > 1:
            d.normalize()
        p = c + d * radius * 0.65
        r = radius * rnd.uniform(0.3, 0.5)
        parts.append((displace(sphere(p, r, segments=20, rings=14), r * 0.22, 3.0 / r, k + seed), mat))
    m.add_fused(parts, voxel=voxel, smooth_iters=4, smooth_factor=0.5, max_faces=12000)


# ============================================================================ truck

def truck_cab():
    """Cab of the delivery truck. Origin: where the cab meets the bed, at bed-floor height (y=0).
    The truck drives toward +x; the camera sees its -z side."""
    m = Model("truck_cab")
    red, cream, chrome = PAINT_RED, PAINT_CREAM, CHROME
    gl = glass("BFD9E8")
    # cabin body and hood, generously rounded like a pressed-steel panel
    m.add(box((0.0, -0.35, -0.72), (1.25, 0.95, 0.72), bevel=0.11, segments=5), red)
    m.add(box((1.15, -0.35, -0.7), (1.85, 0.38, 0.7), bevel=0.1, segments=5), red)
    m.add(box((1.2, 0.36, -0.55), (1.82, 0.4, 0.55), bevel=0.02), red)                       # hood crown
    # door shut lines and hinges
    for z in (-0.725,):
        m.add(box((0.2, -0.3, z - 0.004), (0.205, 0.88, z + 0.002)), BLACK_PLASTIC)
        m.add(box((1.1, -0.3, z - 0.004), (1.105, 0.88, z + 0.002)), BLACK_PLASTIC)
        m.add(box((0.2, -0.3, z - 0.004), (1.105, -0.295, z + 0.002)), BLACK_PLASTIC)
    # grille, headlights
    m.add(box((1.8, -0.3, -0.62), (1.9, 0.3, 0.62), bevel=0.04), chrome)
    for k in range(7):
        m.add(box((1.87, -0.26 + k * 0.08, -0.56), (1.915, -0.225 + k * 0.08, 0.56), bevel=0.006), BLACK_PLASTIC)
    for s in (-1, 1):
        m.add(cyl((1.84, 0.2, s * 0.5), 0.1, 0.09, axis="x", segments=32, bevel=0.015), chrome)
        m.add(cyl((1.89, 0.2, s * 0.5), 0.078, 0.02, axis="x", segments=32), glow("FFF2C4"))
        m.add(cyl((1.82, -0.05, s * 0.6), 0.035, 0.05, axis="x", segments=16), glow("F2A33A"))   # indicators
    # windows with rubber seals
    m.add(box((0.25, 0.45, -0.73), (1.05, 0.85, -0.715), bevel=0.02), gl)
    m.add(box((0.23, 0.43, -0.728), (1.07, 0.87, -0.712), bevel=0.02), RUBBER)
    m.add(box((1.12, 0.45, -0.66), (1.2, 0.85, 0.66), bevel=0.02), gl, transform=rotate_about((1.16, 0.45, 0), "Z", -14))
    m.add(box((0.1, 0.45, -0.6), (0.12, 0.85, 0.6)), gl)
    # cream stripe and door logo
    m.add(box((0.02, 0.18, -0.74), (1.84, 0.3, -0.72), bevel=0.01), cream)
    m.add(box((0.4, -0.25, -0.743), (0.82, 0.17, -0.74)), decal("logo"), uv_scale=1 / 0.42, uv_offset=(0.5 - 0.61 / 0.42, 0.5 + 0.04 / 0.42))
    m.add(box((0.98, -0.05, -0.755), (1.06, 0.0, -0.73), bevel=0.012), chrome)              # door handle
    # mirror arm and head, amber roof beacon, bumper, step
    m.add(rod((1.1, 0.7, -0.74), (1.2, 0.72, -0.88), 0.014), BLACK_PLASTIC)
    m.add(box((1.13, 0.58, -0.94), (1.24, 0.8, -0.86), bevel=0.025), BLACK_PLASTIC)
    m.add(box((1.135, 0.59, -0.865), (1.235, 0.79, -0.858)), CHROME)
    m.add(box((0.45, 0.95, -0.2), (0.85, 0.99, 0.2), bevel=0.015), BLACK_PLASTIC)
    m.add(sphere((0.65, 1.02, 0.0), 0.09, scale=(1, 0.7, 1)), glow("F2A33A"))
    m.add(box((1.75, -0.44, -0.75), (1.97, -0.3, 0.75), bevel=0.045, segments=3), chrome)
    m.add(box((0.25, -0.5, -0.8), (0.95, -0.46, -0.66), bevel=0.01), P("brushed", "B8BCC2"))
    # chassis, fuel tank, exhaust
    m.add(box((-0.1, -0.5, -0.55), (1.8, -0.35, 0.55), bevel=0.01), P("enamel", "2A2628"))
    m.add(cyl((0.6, -0.42, -0.62), 0.12, 0.5, axis="x", segments=24, bevel=0.02), P("brushed", "A9AEB4"))
    m.add(rod((0.15, -0.45, 0.5), (0.15, 1.05, 0.5), 0.035), CHROME)
    # wheel arch
    m.add(torus((1.35, -0.35, -0.69), 0.37, 0.05, axis="z", arc=0.5, segments=28, ring_segments=10), red)
    m.add(torus((1.35, -0.35, -0.66), 0.345, 0.03, axis="z", arc=0.5, segments=28, ring_segments=8), RUBBER)
    return [m.build()]


def truck_bed():
    """3.2 m flat bed behind the cab. Origin at the bed's front-centre (x=0 where the cab begins),
    floor top at y=0. The bed extends to x = -3.2. Camera side (-z) is open."""
    m = Model("truck_bed")
    red, dark = PAINT_RED, P("enamel", "2A2628")
    L = 3.2
    # floor: seven planks with small gaps
    for k in range(7):
        z0 = -0.7 + k * 0.2
        m.add(box((-L, -0.09, z0 + 0.004), (0.0, 0.0, z0 + 0.196), bevel=0.006), TIMBER)
    m.add(box((-L, -0.1, -0.7), (0.0, -0.085, 0.72)), dark)
    m.add(box((-L, -0.2, -0.72), (0.0, -0.09, 0.72), bevel=0.02), red)
    m.add(box((-L - 0.02, -0.48, -0.5), (0.0, -0.2, 0.5)), dark)
    # far rail with posts and planks
    for k in range(6):
        x = -L + 0.08 + k * (L - 0.16) / 5
        m.add(box((x - 0.04, 0.0, 0.64), (x + 0.04, 0.55, 0.72), bevel=0.012), red)
        m.add(cyl((x, 0.29, 0.635), 0.012, 0.01, axis="z", segments=10), CHROME)
    for y in (0.18, 0.4):
        m.add(box((-L, y, 0.66), (0.0, y + 0.1, 0.7), bevel=0.008), TIMBER)
    # tail gate (left end) and short front rail
    m.add(box((-L - 0.06, -0.2, -0.7), (-L, 0.4, 0.72), bevel=0.015), red)
    m.add(box((-0.06, 0.0, -0.7), (0.0, 0.5, 0.72), bevel=0.015), red)
    # rear lights, mud flap, fender
    m.add(box((-L - 0.075, -0.17, -0.67), (-L - 0.05, -0.05, -0.49), bevel=0.01), glow("FF5A4A"))
    m.add(box((-L + 0.3, -0.62, -0.72), (-L + 0.32, -0.22, -0.4)), RUBBER)
    m.add(torus((-L + 0.75, -0.2, -0.71), 0.38, 0.05, axis="z", arc=0.5, segments=28, ring_segments=10), red)
    return [m.build()]


def truck_wheel():
    m = Model("truck_wheel")
    rim, cap = P("enamel", "E2E0D8"), CHROME
    m.add(cyl((0, 0, 0), 0.3, 0.22, axis="z", segments=48, bevel=0.07), RUBBER)
    # tread blocks around the rolling surface
    for k in range(40):
        a = k / 40 * 360
        for s in (-1, 1):
            m.add(box((0.296, -0.018, s * 0.055 - 0.04), (0.322, 0.018, s * 0.055 + 0.04), bevel=0.006), RUBBER,
                  transform=Matrix.Rotation(math.radians(a + (4.5 if s > 0 else 0)), 4, "Z"))
    m.add(torus((0, 0, -0.105), 0.2, 0.018, axis="z", segments=40, ring_segments=8), RUBBER)    # bead
    m.add(cyl((0, 0, -0.06), 0.19, 0.12, axis="z", segments=40, bevel=0.025), rim)
    m.add(cyl((0, 0, -0.125), 0.075, 0.025, axis="z", segments=24, bevel=0.01), cap)
    for k in range(6):
        a = k / 6 * 2 * math.pi
        m.add(cyl((math.cos(a) * 0.12, math.sin(a) * 0.12, -0.125), 0.016, 0.018, axis="z", segments=6), cap)
        m.add(cyl((math.cos(a + 0.52) * 0.155, math.sin(a + 0.52) * 0.155, -0.121), 0.024, 0.006, axis="z", segments=16), P("enamel", "3A3836"))
    return [res(m.build(), 512)]


def parcel_stack():
    """A few other parcels and a mail sack to dress the truck bed and depot."""
    m = Model("parcel_stack")
    m.add(box((-0.3, 0.0, -0.25), (0.3, 0.45, 0.25), bevel=0.012), CARDBOARD)
    m.add(box((-0.25, 0.45, -0.2), (0.2, 0.75, 0.2), bevel=0.012), CARDBOARD, transform=rotate_about((0, 0.45, 0), "Y", 12))
    m.add(box((-0.31, 0.2, -0.257), (0.31, 0.26, -0.25)), TAPE)
    m.add(box((-0.04, 0.0, -0.257), (0.04, 0.452, 0.257)), TAPE)
    m.add(box((0.32, 0.0, -0.2), (0.62, 0.22, 0.15), bevel=0.012), P("cardboard", "A87B4C"))
    m.add(box((0.316, 0.08, -0.205), (0.624, 0.14, 0.155)), TAPE)
    sack = ellipsoid((-0.75, 0.25, 0.0), (0.28, 0.25, 0.22), segments=28, rings=18)
    m.add(displace(sack, 0.025, freq=6, seed=4), P("burlap", "B8A27A"))
    m.add(cyl((-0.75, 0.5, 0.0), 0.06, 0.08, axis="y", segments=16), P("burlap", "A08A62"))
    m.add(torus((-0.75, 0.49, 0.0), 0.065, 0.012, axis="y", segments=20, ring_segments=6), P("rope", "8A6A4A"))
    return [res(m.build(), 1024)]


# ============================================================================ road & scenery

def road_tile():
    """2 m road section centred on x; road surface top at y=0, spans z -1.6..1.6 with verges."""
    m = Model("road_tile")
    m.add(box((-1.0, -0.12, -1.4), (1.0, 0.0, 1.4)), tex("asphalt"), uv_scale=0.5)
    m.add(box((-0.55, 0.0, 0.02), (0.55, 0.003, 0.12)), matte("E9E0C4"))
    for s in (-1, 1):
        m.add(box((-1.0, -0.12, s * 1.4 - (0.12 if s > 0 else 0)), (1.0, 0.06, s * 1.4 + (0.0 if s > 0 else 0.12)), bevel=0.012),
              tex("concrete"), uv_scale=1.0)
    m.add(box((-1.0, -0.1, 1.52), (1.0, 0.04, 4.5)), tex("grass"), uv_scale=0.5)
    m.add(box((-1.0, -0.1, -4.5), (1.0, 0.04, -1.52)), tex("grass"), uv_scale=0.5)
    return [m.build()]


def speedbump():
    m = Model("prop_speedbump")
    for k in range(6):
        c = P("enamel", "E8B030") if k % 2 == 0 else P("rubber", "1E1E1E")
        z0 = -1.35 + k * 0.45
        m.add(cyl((0, -0.06, z0 + 0.225), 0.22, 0.45, axis="z", segments=40, bevel=0.02), c,
              transform=Matrix.Diagonal(V(1.0, 0.55, 1.0, 1)))
    return [res(m.build(), 512)]


def pothole():
    m = Model("prop_pothole")
    rnd = random.Random(3)
    pts = []
    for k in range(24):
        a = k / 24 * 2 * math.pi
        r = 0.42 + rnd.uniform(-0.06, 0.06)
        pts.append((math.cos(a) * r, math.sin(a) * r * 0.85))
    m.add(extrude_outline(pts, -0.02, 0.0, bevel=0.0), P("soil", "2E2A27"), transform=Matrix.Rotation(math.pi / 2, 4, "X"))
    for k in range(14):  # crumbled rim chunks
        a = k / 14 * 2 * math.pi + rnd.uniform(0, 0.3)
        p = V(math.cos(a) * 0.46, 0.004, math.sin(a) * 0.39)
        m.add(displace(ico(p, 0.03 + rnd.uniform(0, 0.03), 2), 0.008, 30, k), P("matte", "4A4644"))
    return [res(m.build(), 512)]


def cobbles():
    """1 m strip of cobblestones (z -1.4..1.4)."""
    m = Model("prop_cobbles")
    m.add(box((-0.5, -0.02, -1.4), (0.5, 0.012, 1.4)), tex("cobble"), uv_scale=1.0)
    return [m.build()]


def tree_round():
    m = Model("tree_round")
    rnd = random.Random(1)
    trunk = sweep(bezier(V(0, 0, 0), V(0.05, 0.5, 0), V(-0.05, 0.9, 0.02), V(0.02, 1.4, 0), 10), 0.13, radius_end=0.07)
    m.add(trunk, BARK)
    for k in range(3):  # limbs into the crown
        a = k / 3 * 2 * math.pi + 0.4
        tip = V(math.cos(a) * 0.45, 1.75 + rnd.uniform(0, 0.2), math.sin(a) * 0.35)
        m.add(sweep(bezier(V(0, 1.1, 0), V(0, 1.35, 0), tip * 0.7 + V(0, 0.3, 0), tip, 6), 0.06, radius_end=0.025), BARK)
    m.add(cyl((0, 0.02, 0), 0.2, 0.06, axis="y", radius2=0.14, segments=20), BARK)                 # root flare
    canopy(m, (0, 1.85, 0), 1.0, seed=11, blobs=18)
    return [m.build()]


def tree_pine():
    m = Model("tree_pine")
    m.add(cyl((0, 1.1, 0), 0.11, 2.2, axis="y", radius2=0.03, segments=16), BARK)
    rnd = random.Random(4)
    parts = []
    needles = P("needles", "2F5A34")
    layers = 10
    parts.append((lathe([(0.0, 0.0), (0.5, 0.0), (0.0, 2.6)], segments=16), needles))     # dense core
    parts[-1][0][0].transform(Matrix.Translation((0, 0.5, 0)))
    for k in range(layers):
        y = 0.45 + k * 0.24
        r = 0.95 * (1 - k / (layers + 0.6))
        n = 12 - k // 2
        for j in range(n):
            a = j / n * 2 * math.pi + rnd.uniform(-0.2, 0.2) + k * 0.4
            # one drooping bough: an elongated lump pointing outward and down
            reach = r * rnd.uniform(0.85, 1.05)
            mid = V(math.cos(a) * reach * 0.5, y - reach * 0.18, math.sin(a) * reach * 0.5)
            bough = ellipsoid((0, 0, 0), (reach * 0.55, 0.09 + 0.06 * r, 0.12 + 0.06 * r), segments=12, rings=8)
            t = Matrix.Translation(mid) @ Matrix.Rotation(-a, 4, "Y") @ Matrix.Rotation(math.radians(-20), 4, "Z")
            bough[0].transform(t)
            parts.append((displace(bough, 0.05, 9, k * 10 + j), needles))
    parts.append((lathe([(0.0, 0.0), (0.14, 0.0), (0.0, 0.55)], segments=12), needles))
    parts[-1][0][0].transform(Matrix.Translation((0, 0.45 + layers * 0.24 - 0.15, 0)))
    m.add_fused(parts, voxel=0.03, smooth_iters=3, smooth_factor=0.5, max_faces=16000)
    return [m.build()]


def bush():
    m = Model("prop_bush")
    rnd = random.Random(2)
    canopy(m, (0, 0.32, 0), 0.42, seed=21, color=P("foliage", "4D7A33"), blobs=9, voxel=0.025, squash=0.6)
    for k in range(9):
        p = V(rnd.uniform(-0.35, 0.35), rnd.uniform(0.35, 0.58), rnd.uniform(-0.32, -0.18))
        m.add(sphere(p, 0.035, segments=10, rings=8), P("satin", rnd.choice(("F07AA8", "F7D24A", "FFFFFF"))))
    return [res(m.build(), 512)]


def house(variant):
    walls, roofc, door = [("brick", "shingle", TEAL), ("plaster", "shingle", "8E3B6B"), ("brick", "shingle", "C7362B")][variant]
    m = Model(f"house_{variant}")
    w, h, d = 3.2, 2.4, 2.4
    m.add(box((-w / 2, 0, -d / 2), (w / 2, h, d / 2), bevel=0.02), tex(walls), uv_scale=1.0)
    m.add(prism([(-w / 2, h), (w / 2, h), (0, h + 1.2)], -d / 2 + 0.02, d / 2 - 0.02), tex(walls), uv_scale=1.0)   # gables
    # roof: two sloped slabs, shingles textured along the slope
    pitch = math.degrees(math.atan2(1.4, w / 2 + 0.2))
    slope = math.hypot(w / 2 + 0.2, 1.4) + 0.05
    for s in (-1, 1):
        # built with the slope along local z so the shingle rows (texture v) run along the ridge
        slab_ = box((-d / 2 - 0.25, -0.06, -slope), (d / 2 + 0.25, 0.0, 0.0), bevel=0.01)
        t = Matrix.Translation((0, h + 1.4, 0)) @ Matrix.Rotation(math.radians(-s * pitch), 4, "Z") @ Matrix.Rotation(math.radians(-s * 90), 4, "Y")
        m.add(slab_, tex("shingle"), uv_scale=1.0, uv_local=True, transform=t)
    m.add(box((0.7, h + 0.3, 0.2), (1.05, h + 1.6, 0.55), bevel=0.01), tex("brick"), uv_scale=1.0)
    m.add(box((0.67, h + 1.6, 0.17), (1.08, h + 1.66, 0.58), bevel=0.01), matte("6B6466"))
    m.add(box((-0.35, 0, -d / 2 - 0.03), (0.35, 1.35, -d / 2 + 0.01), bevel=0.02), matte(door))
    m.add(box((-0.42, 0, -d / 2 - 0.02), (0.42, 1.42, -d / 2 + 0.01), bevel=0.02), matte(CREAM))
    m.add(sphere((0.22, 0.68, -d / 2 - 0.05), 0.035), matte("C9A040"))
    for x in (-1.05, 1.05):
        m.add(box((x - 0.38, 0.9, -d / 2 - 0.03), (x + 0.38, 1.7, -d / 2 + 0.01), bevel=0.02), matte(CREAM))
        m.add(box((x - 0.3, 0.98, -d / 2 - 0.04), (x + 0.3, 1.62, -d / 2 - 0.02)), glow("FFE2A8") if variant == 1 else glass("9FB9C8"))
        m.add(box((x - 0.015, 0.98, -d / 2 - 0.045), (x + 0.015, 1.62, -d / 2 - 0.035)), matte(CREAM))
        m.add(box((x - 0.3, 1.285, -d / 2 - 0.045), (x + 0.3, 1.315, -d / 2 - 0.035)), matte(CREAM))
        m.add(box((x - 0.45, 0.85, -d / 2 - 0.1), (x + 0.45, 0.92, -d / 2 + 0.02)), matte(CREAM))
    return [m.build()]


def fence():
    m = Model("prop_fence")
    paint = P("enamel", "F2EFE6")
    for k in range(5):
        x = -0.8 + k * 0.4
        m.add(prism([(x - 0.06, 0.0), (x + 0.06, 0.0), (x + 0.06, 0.7), (x, 0.78), (x - 0.06, 0.7)], -0.025, 0.025, bevel=0.006), paint)
    for y in (0.22, 0.52):
        m.add(box((-1.0, y, 0.025), (1.0, y + 0.07, 0.05), bevel=0.005), paint)
    return [res(m.build(), 512)]


def lamppost():
    m = Model("prop_lamppost")
    iron = P("enamel", "26303A")
    m.add(cyl((0, 1.4, 0), 0.05, 2.8, axis="y", radius2=0.04, segments=16), iron)
    m.add(cyl((0, 0.15, 0), 0.12, 0.3, axis="y", radius2=0.08, segments=20, bevel=0.02), iron)
    for y in (0.32, 2.2):
        m.add(torus((0, y, 0), 0.06, 0.015, axis="y", segments=20, ring_segments=6), iron)
    m.add(sweep(bezier(V(0, 2.6, 0), V(0, 2.85, 0), V(0.2, 2.9, 0), V(0.4, 2.85, 0), 10), 0.025), iron)
    m.add(lathe([(0.0, 0.0), (0.17, 0.0), (0.09, 0.18), (0.03, 0.22), (0.0, 0.22)], segments=20), iron, transform=Matrix.Translation((0.4, 2.62, 0)))
    m.add(sphere((0.4, 2.63, 0), 0.08), glow("FFE2A8"))
    return [res(m.build(), 512)]


def mailbox():
    m = Model("prop_mailbox")
    m.add(box((-0.04, 0.0, -0.04), (0.04, 0.92, 0.04), bevel=0.008), TIMBER)
    red = P("enamel", RED)
    m.add(box((-0.22, 0.9, -0.14), (0.22, 1.12, 0.14), bevel=0.01), red)
    m.add(cyl((0, 1.12, 0), 0.14, 0.44, axis="x", segments=28), red)
    m.add(box((0.2, 1.05, 0.14), (0.235, 1.32, 0.16), bevel=0.005), P("enamel", "E8B030"))
    m.add(box((-0.225, 0.95, -0.12), (-0.215, 1.2, 0.12)), P("enamel", "A82E25"))
    return [res(m.build(), 512)]


def hill():
    m = Model("prop_hill")
    m.add(displace(ellipsoid((0, 0, 0), (9, 3, 5), segments=48, rings=24), 0.25, 0.4, 2), tex("grass"), uv_scale=0.35)
    return [m.build()]


def cloud():
    """Kept for compatibility; the sky now uses a painted cloud layer (Textures/clouds)."""
    m = Model("prop_cloud")
    rnd = random.Random(5)
    for k in range(6):
        p = V(rnd.uniform(-1.2, 1.2), rnd.uniform(-0.1, 0.4), rnd.uniform(-0.4, 0.4))
        m.add(sphere(p, rnd.uniform(0.45, 0.8), segments=16, rings=10), matte("FFFFFF"))
    return [m.build()]


# ============================================================================ depot

def conveyor():
    """1 m conveyor segment (scaled along x in Unity). Belt top at y=0, centred on x."""
    m = Model("prop_conveyor")
    frame = P("enamel", AMBER)
    m.add(box((-0.5, -0.05, -0.42), (0.5, 0.0, 0.42), bevel=0.004), P("rubber", "2C2B2E"))
    for k in range(5):
        x = -0.4 + k * 0.2
        m.add(cyl((x, -0.075, 0), 0.03, 0.82, axis="z", segments=16), P("brushed", "C9CED4"))
    # far rail stands above the belt; the camera-side rail sits below it so the box stays visible
    m.add(box((-0.5, -0.16, 0.44 - 0.03), (0.5, 0.05, 0.44 + 0.03), bevel=0.006), frame)
    m.add(box((-0.5, -0.17, -0.47), (0.5, -0.06, -0.41), bevel=0.006), frame)
    return [res(m.build(), 512)]


def depot_bin():
    m = Model("prop_bin")
    blue = P("plastic", "3F6E96")
    m.add(box((-0.85, 0.0, -0.6), (0.85, 0.06, 0.6), bevel=0.02), blue)
    m.add(box((-0.85, 0.0, 0.54), (0.85, 0.55, 0.6), bevel=0.02), blue)
    m.add(box((-0.85, 0.0, -0.6), (-0.79, 0.55, 0.6), bevel=0.02), blue)
    m.add(box((0.79, 0.0, -0.6), (0.85, 0.55, 0.6), bevel=0.02), blue)
    m.add(box((-0.85, 0.0, -0.6), (0.85, 0.12, -0.54), bevel=0.02), blue)
    for x in (-0.6, 0.6):
        for z in (-0.45, 0.45):
            m.add(cyl((x, -0.08, z), 0.08, 0.06, axis="z", segments=24, bevel=0.01), RUBBER)
            m.add(cyl((x, -0.08, z), 0.03, 0.065, axis="z", segments=12), P("brushed", "C9CED4"))
    return [res(m.build(), 512)]


def chute():
    """2 m metal slide (rotated in Unity), top surface at y=0, centred on x."""
    m = Model("prop_chute")
    m.add(box((-1.0, -0.05, -0.45), (1.0, 0.0, 0.45)), P("brushed", "B8BCC2"))
    m.add(box((-1.0, -0.05, 0.46 - 0.02), (1.0, 0.18, 0.46 + 0.02), bevel=0.01), P("enamel", AMBER))
    m.add(box((-1.0, -0.12, -0.48), (1.0, -0.02, -0.44), bevel=0.01), P("enamel", AMBER))
    return [res(m.build(), 512)]


def bumper():
    m = Model("prop_bumper")
    m.add(box((-0.08, 0.0, -0.5), (0.08, 0.45, 0.5), bevel=0.04, segments=3), P("rubber", "B8322A"))
    for k in range(4):
        m.add(box((-0.081, 0.05 + k * 0.1, -0.5), (0.081, 0.09 + k * 0.1, 0.5)), P("enamel", "E8B030"))
    return [res(m.build(), 512)]


def robot_arm():
    """Industrial arm in parts: Base (origin at floor), Upper (pivot at shoulder), Fore (pivot at elbow),
    Grip (pivot at wrist). Unity poses the joints."""
    orange, dark, steel = P("enamel", "E07A1F"), P("enamel", "34312F"), P("brushed", "C9CED4")
    base = Model("arm_base")
    base.add(cyl((0, 0.06, 0), 0.4, 0.12, axis="y", segments=40, bevel=0.02), dark)
    for k in range(8):
        a = k / 8 * 2 * math.pi
        base.add(cyl((math.cos(a) * 0.34, 0.125, math.sin(a) * 0.34), 0.022, 0.02, axis="y", segments=8), steel)
    base.add(cyl((0, 0.45, 0), 0.22, 0.6, axis="y", radius2=0.2, segments=36, bevel=0.04), orange)
    base.add(cyl((0, 0.8, 0), 0.17, 0.44, axis="z", segments=32, bevel=0.03), dark)
    b = res(base.build(), 512)
    up = Model("Upper")
    up.add(box((-0.11, 0.0, -0.11), (0.11, 1.1, 0.11), bevel=0.06, segments=4), orange)
    up.add(cyl((0, 1.1, 0), 0.14, 0.3, axis="z", segments=32, bevel=0.02), dark)
    up.add(sweep(bezier(V(0.11, 0.1, -0.06), V(0.2, 0.4, -0.06), V(0.2, 0.8, -0.06), V(0.11, 1.0, -0.06), 10), 0.018), RUBBER)
    u = res(up.build(origin=(0, 0.8, 0), parent=b), 512)
    fo = Model("Fore")
    fo.add(box((-0.08, 0.0, -0.08), (0.08, 0.9, 0.08), bevel=0.045, segments=4), orange)
    fo.add(cyl((0, 0.9, 0), 0.1, 0.22, axis="z", segments=28, bevel=0.02), dark)
    f = res(fo.build(origin=(0, 1.9, 0), parent=u, parent_origin=(0, 0.8, 0)), 512)
    gr = Model("Grip")
    gr.add(box((-0.08, 0.0, -0.18), (0.08, 0.1, 0.18), bevel=0.02), steel)
    for s in (-1, 1):
        gr.add(box((-0.04, 0.0, s * 0.2 - 0.03), (0.04, -0.25, s * 0.2 + 0.03), bevel=0.01), dark)
        gr.add(box((-0.06, -0.25, s * 0.2 - 0.04), (0.06, -0.2, s * 0.18), bevel=0.01), RUBBER)
    res(gr.build(origin=(0, 2.8, 0), parent=f, parent_origin=(0, 1.9, 0)), 256)
    return [b]


def rack():
    m = Model("prop_rack")
    blue, beam = P("enamel", "2F5F8F"), P("enamel", "E07B1E")
    rnd = random.Random(7)
    for x in (-1.4, 1.4):
        for z in (-0.4, 0.4):
            m.add(box((x - 0.05, 0, z - 0.05), (x + 0.05, 3.2, z + 0.05), bevel=0.006), blue)
        for y in (0.6, 1.6, 2.6):  # cross bracing
            m.add(rod((x, y - 0.4, -0.4), (x, y + 0.4, 0.4), 0.012), blue)
    for y in (0.3, 1.3, 2.3):
        m.add(box((-1.45, y, -0.45), (1.45, y + 0.08, 0.45), bevel=0.008), beam)
        x = -1.3
        while x < 1.1:
            w = rnd.uniform(0.3, 0.6)
            h = rnd.uniform(0.3, 0.75)
            c = rnd.choice(("B98A55", "A87B4C", "C29A68"))
            m.add(box((x, y + 0.08, -0.35), (x + w, y + 0.08 + h, 0.35), bevel=0.01), P("cardboard", c))
            m.add(box((x - 0.003, y + 0.08 + h * 0.45, -0.353), (x + w + 0.003, y + 0.08 + h * 0.55, 0.353)), TAPE)
            x += w + 0.06
    return [m.build()]


def hanging_lamp():
    m = Model("prop_hanglamp")
    m.add(rod((0, 0, 0), (0, 1.5, 0), 0.008), RUBBER)
    m.add(lathe([(0.03, 0.0), (0.06, -0.02), (0.32, -0.25), (0.33, -0.27)], segments=36), P("enamel", "2F5E5A"))
    m.add(cyl((0, -0.03, 0), 0.04, 0.08, axis="y", segments=16), P("brushed", "C9CED4"))
    m.add(sphere((0, -0.16, 0), 0.08), glow("FFE2A8"))
    return [res(m.build(), 256)]


def depot_wall():
    """10 m wall section with high windows, origin at floor level, wall face at z=0."""
    m = Model("depot_wall")
    m.add(box((-5, 0, 0), (5, 7, 0.3)), tex("concrete"), uv_scale=0.4)
    m.add(box((-5, 0, -0.02), (5, 1.2, 0.0)), tex("concrete"), uv_scale=0.8)
    for x in (-5, -2.5, 0, 2.5):  # tilt-up panel joints
        m.add(box((x - 0.012, 0, -0.025), (x + 0.012, 7, -0.005)), matte("6B6466"))
    m.add(box((-5, 1.2, -0.03), (5, 1.32, 0.0)), matte("E0A23A"))
    for x in (-3.0, 0.0, 3.0):
        m.add(box((x - 1.1, 3.8, -0.03), (x + 1.1, 5.8, 0.0), bevel=0.02), matte("4A4E54"))
        m.add(box((x - 1.0, 3.9, -0.04), (x + 1.0, 5.7, -0.02)), glow("E8F0F6"))
        for k in range(1, 4):
            m.add(box((x - 1.0 + k * 0.5 - 0.015, 3.9, -0.05), (x - 1.0 + k * 0.5 + 0.015, 5.7, -0.03)), matte("4A4E54"))
        m.add(box((x - 1.0, 4.78, -0.05), (x + 1.0, 4.82, -0.03)), matte("4A4E54"))
    return [m.build()]


def depot_floor():
    m = Model("depot_floor")
    m.add(box((-5, -0.2, -4), (5, 0.0, 4)), tex("concrete"), uv_scale=0.3)
    for z in (-1.4, 1.4):
        m.add(box((-5, 0.0, z - 0.05), (5, 0.002, z + 0.05)), matte("E8B030"))
    return [m.build()]


# ============================================================================ doorstep

def step():
    """One stair step: tread top at y=0 (front edge at x=0, extends +x by 0.3), riser below."""
    m = Model("prop_step")
    # the riser runs well below ground so Unity can place steps at any height without stretching them
    m.add(box((0.0, -3.0, -0.9), (0.32, 0.0, 0.9), bevel=0.01), tex("concrete"), uv_scale=1.0)
    m.add(box((-0.02, -0.04, -0.91), (0.32, 0.0, 0.91), bevel=0.012), tex("concrete"), uv_scale=1.4)
    return [m.build()]


def porch():
    """Porch floor top at y=0, from x=0 to 4, house wall at z=1.4."""
    m = Model("porch")
    m.add(box((0.0, -0.25, -1.0), (4.0, 0.0, 1.4), bevel=0.01), tex("wood"), uv_scale=1.2)
    m.add(box((0.0, -1.6, 1.4), (4.6, 3.2, 1.7)), tex("brick"), uv_scale=1.0)
    m.add(box((0.0, 3.2, 0.6), (4.6, 3.35, 1.8), bevel=0.02), matte("6B4A3A"))
    for x in (0.1, 3.9):
        m.add(box((x - 0.07, 0.0, -0.95), (x + 0.07, 3.2, -0.81), bevel=0.02), matte(CREAM))
    # door
    m.add(box((1.6, 0.0, 1.36), (2.6, 2.2, 1.42), bevel=0.03), matte(TEAL))
    for y0, y1 in ((0.15, 1.15),):
        for x0 in (1.72, 2.14):
            m.add(box((x0, y0, 1.345), (x0 + 0.34, y1, 1.36), bevel=0.01), matte("287A76"))
    m.add(box((1.75, 1.35, 1.34), (2.45, 1.95, 1.37)), glass("BFD9E8"))
    m.add(sphere((2.45, 1.05, 1.32), 0.04), matte("C9A040"))
    m.add(torus((2.1, 1.55, 1.33), 0.08, 0.012, axis="z", segments=20, ring_segments=6), matte("C9A040"))
    m.add(box((1.45, 0.0, 1.36), (2.75, 2.35, 1.4), bevel=0.03), matte(CREAM))
    m.add(box((3.0, 1.0, 1.35), (4.1, 2.1, 1.4), bevel=0.02), matte(CREAM))
    m.add(box((3.08, 1.08, 1.33), (4.02, 2.02, 1.36)), glow("FFE2A8"))
    root = m.build()
    # doormat, flower pots (baked details)
    d = Model("porch_props")
    d.add(box((1.55, 0.0, 0.3), (2.65, 0.025, 1.2), bevel=0.008), P("burlap", "8A6A44"))
    for i, x in enumerate((0.6, 3.4)):
        d.add(lathe([(0.0, 0), (0.15, 0), (0.2, 0.3), (0.22, 0.31), (0.22, 0.34), (0.0, 0.34)], segments=28), P("terracotta", "B8643A"),
              transform=Matrix.Translation((x, 0, 1.0)))
        d.add(cyl((x, 0.33, 1.0), 0.19, 0.02, axis="y", segments=24), P("soil", "4A3628"))
        canopy(d, (x, 0.5, 1.0), 0.25, seed=40 + i, color=P("foliage", "4D7A33"), blobs=8, voxel=0.018, squash=0.7)
        rnd = random.Random(60 + i)
        for k in range(7):
            a = rnd.uniform(0, 6.28)
            d.add(sphere((x + math.cos(a) * 0.17, 0.56 + rnd.uniform(0, 0.12), 1.0 + math.sin(a) * 0.14 - 0.06), 0.03, segments=10, rings=8),
                  P("satin", ("F07AA8", "F7D24A")[k % 2]))
    res(d.build(parent=root), 1024)
    return [root]


def courier():
    """Dash the courier, in parts for procedural animation. Origin at the feet; faces -z (camera).
    Children: Body, Head, ArmL, ArmR (pivots at shoulders), LegL, LegR (pivots at hips)."""
    uni, skin, cap = P("cloth", "C7362B"), P("skin", "D9A37E"), P("cloth", "1F2A44")
    trousers, shoe, leather = P("cloth", "2A3550"), P("lacquer", "2A2628"), P("lacquer", "6B4A2E")
    root = empty("courier")
    body = Model("Body")
    body.add_fused([(ellipsoid((0, 1.13, 0), (0.19, 0.25, 0.12), segments=32, rings=20), uni),
                    (ellipsoid((0, 1.3, 0), (0.23, 0.08, 0.12), segments=28, rings=14), uni),
                    (ellipsoid((0, 0.84, 0), (0.165, 0.13, 0.115), segments=28, rings=16), trousers)],
                   voxel=0.007, smooth_iters=5)
    body.add(cyl((0, 0.985, 0), 0.172, 0.05, axis="y", segments=40), P("plastic", "E8B030"))      # reflective band
    body.add(torus((0, 1.38, 0), 0.06, 0.018, axis="y", segments=24, ring_segments=8), uni)        # collar
    body.add(box((-0.11, 1.16, -0.128), (-0.03, 1.21, -0.112), bevel=0.006), P("cloth", "EFE6D2"))  # name badge
    body.add(cyl((0, 1.43, 0), 0.05, 0.09, axis="y", segments=20), skin)                          # neck
    body.add(rod((-0.17, 1.31, -0.1), (0.15, 0.9, -0.13), 0.01), leather)                         # satchel strap
    body.add(box((0.1, 0.78, -0.17), (0.3, 0.96, -0.1), bevel=0.02), leather)                     # satchel
    body.add(box((0.1, 0.9, -0.177), (0.3, 0.965, -0.1), bevel=0.012), leather)
    body.add(box((-0.17, 0.75, -0.125), (0.17, 0.78, 0.125), bevel=0.008), leather)                # belt
    res(body.build(parent=root), 512)
    head = Model("Head")
    head.add_fused([(ellipsoid((0, 1.56, 0), (0.098, 0.122, 0.108), segments=32, rings=20), skin),
                    (ellipsoid((0, 1.505, -0.035), (0.075, 0.05, 0.07)), skin),                     # jaw
                    (sphere((0, 1.55, -0.108), 0.02), skin),                                         # nose
                    (ellipsoid((-0.097, 1.56, 0.005), (0.015, 0.03, 0.022)), skin),
                    (ellipsoid((0.097, 1.56, 0.005), (0.015, 0.03, 0.022)), skin)],
                   voxel=0.004, smooth_iters=4)
    head.add(ellipsoid((0, 1.6, 0.03), (0.1, 0.07, 0.085)), P("cloth", "4A3020"))                    # hair at the back
    head.add(ellipsoid((0, 1.645, -0.005), (0.106, 0.055, 0.112), segments=32, rings=16), cap)
    head.add(box((-0.08, 1.628, -0.19), (0.08, 1.638, -0.09), bevel=0.012), cap)
    for s in (-1, 1):
        head.add(sphere((s * 0.035, 1.575, -0.094), 0.012, segments=16, rings=10), P("lacquer", "15100E"))
        head.add(box((s * 0.035 - 0.02, 1.597, -0.1), (s * 0.035 + 0.02, 1.604, -0.088)), P("cloth", "4A3020"))
    head.add(torus((0, 1.515, -0.098), 0.025, 0.005, axis="z", arc=0.4, start=0.55, segments=16, ring_segments=6), P("skin", "9A5A4E"))
    res(head.build(origin=(0, 1.38, 0), parent=root), 512)
    for s, name in ((-1, "ArmL"), (1, "ArmR")):
        a = Model(name)
        a.add_fused([(ellipsoid((s * 0.255, 1.18, 0), (0.06, 0.15, 0.06)), uni),
                     (ellipsoid((s * 0.265, 0.95, 0), (0.05, 0.14, 0.05)), uni)], voxel=0.006, smooth_iters=4)
        a.add(cyl((s * 0.268, 0.82, 0), 0.046, 0.03, axis="y", segments=20), uni)                    # cuff
        a.add_fused([(ellipsoid((s * 0.27, 0.75, 0), (0.035, 0.055, 0.045)), skin),
                     (ellipsoid((s * 0.275, 0.705, -0.01), (0.03, 0.035, 0.035)), skin),
                     (ellipsoid((s * 0.255, 0.75, -0.04), (0.012, 0.03, 0.012)), skin)], voxel=0.004)
        res(a.build(origin=(s * 0.25, 1.3, 0), parent=root), 256)
        l = Model("LegL" if s < 0 else "LegR")
        l.add_fused([(ellipsoid((s * 0.09, 0.55, 0), (0.075, 0.2, 0.075)), trousers),
                     (ellipsoid((s * 0.095, 0.25, 0), (0.06, 0.2, 0.06)), trousers)], voxel=0.006, smooth_iters=4)
        l.add_fused([(ellipsoid((s * 0.095, 0.055, -0.04), (0.055, 0.055, 0.12)), shoe)], voxel=0.006)
        l.add(box((s * 0.095 - 0.056, 0.0, -0.16), (s * 0.095 + 0.056, 0.018, 0.08), bevel=0.01), P("rubber", "D9D2C4"))
        res(l.build(origin=(s * 0.1, 0.72, 0), parent=root), 256)
    return [root]


def street_tile():
    m = Model("street_tile")
    m.add(box((-1.0, -0.15, -3.0), (1.0, 0.0, -0.9)), tex("asphalt"), uv_scale=0.5)
    m.add(box((-1.0, -0.15, -0.9), (1.0, 0.12, 0.6)), tex("concrete"), uv_scale=0.5)
    m.add(box((-1.0, 0.12, -0.9), (1.0, 0.125, -0.85)), matte("A39A92"))
    for x in (-1.0, 0.0):  # slab joints
        m.add(box((x - 0.006, 0.12, -0.9), (x + 0.006, 0.124, 0.6)), matte("8C8682"))
    m.add(box((-1.0, -0.15, 0.6), (1.0, 0.1, 5.0)), tex("grass"), uv_scale=0.5)
    return [m.build()]


# ============================================================================ ship, plane, catapult

def ship_deck():
    """Ferry deck section around the box. Deck top at y=0, spans x -3..3."""
    m = Model("ship_deck")
    m.add(box((-3.2, -0.2, -1.0), (3.2, 0.0, 1.6)), tex("wood"), uv_scale=1.2)
    root = m.build()
    f = Model("ship_fittings")
    white, red = P("enamel", "F2EFE8"), P("enamel", RED)
    f.add(box((-3.2, -1.6, -1.05), (3.2, -0.2, 1.65)), white)
    f.add(box((-3.2, -0.6, -1.06), (3.2, -0.4, 1.66)), red)
    for k in range(13):
        x = -3.0 + k * 0.5
        f.add(rod((x, 0.0, 1.5), (x, 0.9, 1.5), 0.022), white)
    f.add(rod((-3.1, 0.9, 1.5), (3.1, 0.9, 1.5), 0.032), white)
    f.add(rod((-3.1, 0.5, 1.5), (3.1, 0.5, 1.5), 0.018), white)
    f.add(torus((1.8, 0.55, 1.45), 0.22, 0.06, axis="z", segments=32, ring_segments=12), P("plastic", "E8552E"))
    for k in range(4):
        f.add(torus((1.8, 0.55, 1.45), 0.22, 0.062, axis="z", arc=0.08, start=k * 0.25, segments=6, ring_segments=12), P("plastic", "F2EFE8"))
    f.add(cyl((-2.4, 1.6, 0.9), 0.35, 3.2, axis="y", segments=32), red)
    f.add(cyl((-2.4, 2.9, 0.9), 0.36, 0.5, axis="y", segments=32), P("enamel", "2A2628"))
    f.add(box((2.3, 0.0, 0.3), (2.9, 0.5, 0.9), bevel=0.012), TIMBER)
    f.add(box((2.28, 0.2, 0.28), (2.92, 0.26, 0.92)), P("enamel", "3A3836"))
    res(f.build(parent=root), 1024)
    return [root]


def waves():
    """A strip of sea, 12 m long, origin at mean water level (rolling swell along x)."""
    m = Model("prop_waves")

    def h(x, z):
        return 0.11 * math.sin(x * math.pi) + 0.03 * math.sin(x * 2.7 + z * 1.3) + 0.02 * math.sin(z * 2.1 - x * 0.7)
    m.add(slab(-6, 6, -7, 7, -0.6, h, 96, 28), tex("water"), uv_scale=0.25)
    return [m.build()]


def plane_hold():
    """Cargo hold of a mail plane, cutaway toward the camera. Floor top at y=0, spans x -3..3."""
    m = Model("plane_hold")
    m.add(box((-3.2, -0.08, -1.0), (3.2, 0.0, 1.3)), tex("treadplate"), uv_scale=1.0)
    root = m.build()
    s = Model("hold_shell")
    alu, rib = P("brushed", "A9AEB4"), P("enamel", "7D8288")
    for k in range(7):
        x = -3.0 + k * 1.0
        s.add(torus((x, 0.8, 0.2), 1.25, 0.045, axis="x", arc=0.5, start=0.25, segments=32, ring_segments=8), rib)
    s.add(box((-3.2, 0.0, 1.3), (3.2, 1.9, 1.38)), alu)
    for k in range(5):
        x = -2.4 + k * 1.2
        s.add(torus((x, 1.1, 1.28), 0.22, 0.05, axis="z", segments=32, ring_segments=10), P("enamel", AMBER))
        s.add(cyl((x, 1.1, 1.3), 0.2, 0.02, axis="z", segments=32), glow("CFE6F7"))
        for j in range(12):  # rivets around the porthole
            a = j / 12 * 2 * math.pi
            s.add(sphere((x + math.cos(a) * 0.3, 1.1 + math.sin(a) * 0.3, 1.295), 0.008, segments=8, rings=6), alu)
    s.add(box((-3.2, 1.9, -0.2), (3.2, 2.0, 1.38)), alu)
    # fuselage belly under the cutaway floor: painted skin, livery stripe, panel seams
    skin = P("enamel", "E9E7E1")
    s.add(box((-3.2, -1.1, -1.0), (3.2, -0.08, 1.3), bevel=0.04, segments=3), skin)
    s.add(box((-3.21, -0.55, -1.01), (3.21, -0.4, 1.31)), P("enamel", RED))
    for x in (-2.0, -0.6, 0.8, 2.2):
        s.add(box((x - 0.006, -1.1, -1.012), (x + 0.006, -0.1, -1.004)), P("enamel", "B9B7B0"))
        for y in (-0.95, -0.25):
            s.add(sphere((x + 0.25, y, -1.006), 0.008, segments=8, rings=6), alu)
    for k in range(9):  # cargo net
        s.add(rod((-3.0 + k * 0.4, 0.0, 1.22), (-3.2 + k * 0.4, 1.6, 1.22), 0.009), P("rope", "C9B48A"))
        s.add(rod((-3.2 + k * 0.4, 0.0, 1.22), (-3.0 + k * 0.4, 1.6, 1.22), 0.009), P("rope", "C9B48A"))
    res(s.build(parent=root), 1024)
    return [root]


def catapult():
    """Wooden catapult. Children: Arm (pivot at the axle). Origin at ground level, centred."""
    wood, rope, iron = TIMBER, P("rope", "C9B48A"), P("brushed", "5E6268")
    base = Model("catapult")
    for s in (-1, 1):
        base.add(box((-1.6, 0.0, s * 0.7 - 0.08), (1.6, 0.18, s * 0.7 + 0.08), bevel=0.02), wood)
        base.add(hull([(-0.6, 0.18, s * 0.7 - 0.07), (0.6, 0.18, s * 0.7 - 0.07), (0.0, 1.4, s * 0.7 - 0.07),
                       (-0.6, 0.18, s * 0.7 + 0.07), (0.6, 0.18, s * 0.7 + 0.07), (0.0, 1.4, s * 0.7 + 0.07)], bevel=0.02), wood)
        for x in (-0.45, 0.45):  # iron straps
            base.add(box((x - 0.04, 0.17, s * 0.7 - 0.09), (x + 0.04, 0.2, s * 0.7 + 0.09)), iron)
    for x in (-1.4, 1.4):
        base.add(box((x - 0.08, 0.0, -0.78), (x + 0.08, 0.18, 0.78), bevel=0.02), wood)
    base.add(cyl((0.0, 1.3, 0), 0.08, 1.6, axis="z", segments=20), iron)
    for x in (-1.3, 1.3):
        for z in (-0.78, 0.78):
            base.add(cyl((x, 0.0, z), 0.3, 0.12, axis="z", segments=32, bevel=0.03), wood)
            base.add(torus((x, 0.0, z), 0.3, 0.02, axis="z", segments=32, ring_segments=6), iron)
            base.add(cyl((x, 0.0, z - 0.07 * (1 if z > 0 else -1)), 0.06, 0.04, axis="z", segments=16), iron)
    b = base.build()
    arm = Model("Arm")
    arm.add(box((-0.08, -0.08, -0.12), (2.5, 0.08, 0.12), bevel=0.02), wood)
    arm.add(box((-0.9, -0.3, -0.35), (-0.1, 0.25, 0.35), bevel=0.04), P("matte", "6B6466"))
    for k in range(4):
        arm.add(torus((0.3 + k * 0.4, 0.0, 0.0), 0.1, 0.022, axis="x", segments=16, ring_segments=6), rope)
    a = res(arm.build(origin=(0.0, 1.3, 0), parent=b), 512)
    # the bucket hangs from the arm tip and is kept level in Unity
    bucket = Model("Bucket")
    bucket.add(box((-0.62, -0.06, -0.3), (0.62, 0.0, 0.3), bevel=0.02), wood)
    for sx in (-1, 1):
        bucket.add(box((sx * 0.62 - 0.04, -0.06, -0.3), (sx * 0.62 + 0.04, 0.22, 0.3), bevel=0.02), wood)
    bucket.add(box((-0.62, -0.06, 0.26), (0.62, 0.22, 0.3), bevel=0.02), wood)
    res(bucket.build(origin=(2.5, 1.3, 0), parent=a, parent_origin=(0.0, 1.3, 0)), 512)
    return [b]


def haystack():
    m = Model("prop_haystack")
    m.add(displace(ellipsoid((0, 0.5, 0), (1.4, 0.75, 1.1), segments=40, rings=20), 0.08, 5, 3), tex("hay"), uv_scale=1.0)
    rnd = random.Random(9)
    for k in range(40):
        p = V(rnd.uniform(-1.2, 1.2), rnd.uniform(0.6, 1.1), rnd.uniform(-0.9, 0.2))
        m.add(rod(p, p + V(rnd.uniform(-0.15, 0.15), rnd.uniform(0.05, 0.2), rnd.uniform(-0.1, 0.1)), 0.007), tex("hay"), uv_scale=4.0)
    return [m.build()]


def tower():
    m = Model("prop_tower")
    m.add(cyl((0, 3.0, 0), 1.2, 6.0, axis="y", radius2=1.0, segments=40), tex("cobble"), uv_scale=0.6)
    m.add(lathe([(0.0, 0.0), (1.45, 0.0), (0.0, 3.0)], segments=40, smooth=False), tex("shingle"), uv_scale=1.0, transform=Matrix.Translation((0, 6.0, 0)))
    for k in range(3):
        y = 1.5 + k * 1.6
        m.add(box((-0.25, y, -1.22), (0.25, y + 0.7, -1.0), bevel=0.05), glow("FFD28A"))
    m.add(sphere((0, 9.1, 0), 0.15), glow("F2B632"))
    m.add(rod((0, 9.0, 0), (0, 9.8, 0), 0.03), matte("C9A040"))
    return [m.build()]


# ============================================================================ reveal room

def reveal_room():
    """Customer's living room. Table top at y=0 centred on the origin; camera looks from -z."""
    m = Model("reveal_room")
    m.add(box((-6, -0.85, -4), (6, -0.8, 4)), tex("wood"), uv_scale=0.8)
    m.add(box((-6, -0.85, 2.5), (6, 4, 2.6)), tex("plaster"), uv_scale=0.6)
    m.add(box((-6, -0.85, 2.45), (6, 0.1, 2.5)), matte("EFE6D2"))
    m.add(box((-6, 0.1, 2.44), (6, 0.16, 2.5), bevel=0.01), matte("EFE6D2"))                       # dado rail
    root = m.build()

    t = Model("reveal_table")
    walnut = P("varnish", "7A4E30")
    t.add(box((-1.3, -0.06, -0.8), (1.3, 0.0, 0.8), bevel=0.02), walnut)
    t.add(box((-1.32, -0.004, -0.82), (1.32, 0.003, 0.82), bevel=0.003), P("gingham", "C94A4A", "F4EFE6"))
    t.add(box((-1.33, -0.3, -0.83), (1.33, 0.0, -0.81), bevel=0.003), P("ginghamv", "C94A4A", "F4EFE6"))
    for x in (-1.15, 1.15):
        for z in (-0.65, 0.65):
            t.add(cyl((x, -0.45, z), 0.045, 0.8, axis="y", radius2=0.032, segments=20), walnut)
    res(t.build(parent=root), 1024)

    r = Model("reveal_rug")
    r.add(box((-2.2, -0.8, -1.8), (2.2, -0.77, 1.6), bevel=0.01), P("felt", "2F7F7B"))
    r.add(box((-2.0, -0.769, -1.6), (2.0, -0.768, 1.4)), P("felt", "C8A060"))
    r.add(box((-1.9, -0.768, -1.5), (1.9, -0.767, 1.3)), P("felt", "2F7F7B"))
    res(r.build(parent=root), 512)

    d = Model("reveal_decor")
    cream = P("enamel", "EFE6D2")
    # window with curtains
    d.add(box((-3.6, 0.6, 2.4), (-1.6, 2.6, 2.48), bevel=0.02), cream)
    d.add(box((-2.62, 0.7, 2.37), (-2.58, 2.5, 2.4)), cream)
    d.add(box((-3.5, 1.58, 2.37), (-1.7, 1.62, 2.4)), cream)
    for x in (-3.8, -1.45):
        for k in range(5):  # folds
            d.add(cyl((x - 0.16 + k * 0.08, 1.6, 2.33), 0.05, 2.4, axis="y", segments=12), P("cloth", "C85A5A"))
    d.add(rod((-4.1, 2.82, 2.33), (-1.15, 2.82, 2.33), 0.02), P("gold", "C9A040"))
    # picture frames
    for x, w, h, c in ((0.6, 0.6, 0.45, "D9A441"), (1.5, 0.4, 0.55, "3E8A86"), (2.3, 0.5, 0.35, "B8473B")):
        d.add(box((x - w / 2, 1.5, 2.42), (x + w / 2, 1.5 + h, 2.47), bevel=0.012), P("gold", "B8923A"))
        d.add(box((x - w / 2 + 0.05, 1.55, 2.41), (x + w / 2 - 0.05, 1.45 + h, 2.42)), P("swirl", c, "EFE6D2"))
    # armchair
    velvet = P("cloth", "7E3560")
    d.add(box((2.6, -0.8, 1.4), (4.0, -0.3, 2.3), bevel=0.14, segments=5), velvet)
    d.add(box((2.6, -0.3, 2.0), (4.0, 0.5, 2.3), bevel=0.14, segments=5), velvet)
    for x in (2.6, 4.0):
        d.add(box((x - 0.12, -0.3, 1.4), (x + 0.12, 0.0, 2.3), bevel=0.1, segments=4), velvet)
    # potted plant
    d.add(lathe([(0.0, 0), (0.2, 0), (0.25, 0.4), (0.27, 0.42), (0.0, 0.42)], segments=28), P("terracotta", "B8643A"),
          transform=Matrix.Translation((-2.6, -0.8, 1.8)))
    for k in range(9):
        a = k / 9 * 2 * math.pi
        tip = V(-2.6 + math.cos(a) * 0.5, 0.4 + (k % 3) * 0.2, 1.8 + math.sin(a) * 0.3)
        d.add(sweep(bezier(V(-2.6, -0.4, 1.8), V(-2.6, 0.0, 1.8), tip + V(0, 0.2, 0), tip, 10), 0.05, radius_end=0.01, profile_scale=(1, 0.3)),
              P("foliage", "4D7A33"))
    # table lamp
    brass = P("gold", "C9A040")
    d.add(cyl((-1.1, 0.25, 1.0), 0.03, 0.5, axis="y", segments=16), brass)
    d.add(lathe([(0.12, 0.0), (0.25, 0.0), (0.18, 0.25), (0.08, 0.25)], segments=32), P("cloth", "F3E9D2"), transform=Matrix.Translation((-1.1, 0.5, 1.0)))
    d.add(cyl((-1.1, 0.02, 1.0), 0.14, 0.04, axis="y", segments=28, bevel=0.01), brass)
    res(d.build(parent=root), 1024)
    return [root]


ALL = {
    "truck_cab": truck_cab, "truck_bed": truck_bed, "truck_wheel": truck_wheel, "parcel_stack": parcel_stack,
    "road_tile": road_tile, "speedbump": speedbump, "pothole": pothole, "cobbles": cobbles,
    "tree_round": tree_round, "tree_pine": tree_pine, "bush": bush, "house_0": lambda: house(0), "house_1": lambda: house(1),
    "house_2": lambda: house(2), "fence": fence, "lamppost": lamppost, "mailbox": mailbox, "hill": hill, "cloud": cloud,
    "conveyor": conveyor, "bin": depot_bin, "chute": chute, "bumper": bumper, "robot_arm": robot_arm, "rack": rack,
    "hanglamp": hanging_lamp, "depot_wall": depot_wall, "depot_floor": depot_floor,
    "step": step, "porch": porch, "courier": courier, "street_tile": street_tile,
    "ship_deck": ship_deck, "waves": waves, "plane_hold": plane_hold, "catapult": catapult, "haystack": haystack,
    "tower": tower, "reveal_room": reveal_room,
}
