using System.Collections.Generic;
using UnityEngine;

namespace HWC.Visuals
{
    /// <summary>Textures generated by ArtSource/make_textures.py (Resources/Textures) plus a few runtime ones.</summary>
    public static class TextureLibrary
    {
        static readonly Dictionary<string, Texture2D> cache = new Dictionary<string, Texture2D>();

        public static Texture2D Get(string name)
        {
            if (cache.TryGetValue(name, out var t) && t != null) return t;
            t = Resources.Load<Texture2D>("Textures/" + name);
            cache[name] = t;
            return t;
        }

        /// <summary>Material for "tex_name": uses Textures/name and Textures/name_n as normal map if present.</summary>
        public static Material MaterialFor(string name)
        {
            var tex = Get(name);
            var nrm = Get(name + "_n");
            if (tex == null) return Mat.Lit(Palette.Kraft, 0.25f);
            var mask = Get(name + "_mask");
            if (mask != null) return Mat.Baked("tex_" + name, tex, nrm, mask);
            float smooth = name.Contains("tape") ? 0.55f : (name.Contains("wood") ? 0.3f : 0.18f);
            return Mat.Textured("tex_" + name, tex, Color.white, smooth, nrm, 0.8f);
        }

        /// <summary>Material for "bake_model": Textures/Baked/model(.png, _n, _mask) from ArtSource/pbr.py.</summary>
        public static Material BakedMaterial(string model)
        {
            var alb = Get("Baked/" + model);
            if (alb == null)
            {
                Debug.LogWarning("[TextureLibrary] missing baked textures for " + model);
                return Mat.Lit(Color.gray, 0.3f);
            }
            return Mat.Baked("bake_" + model, alb, Get("Baked/" + model + "_n"), Get("Baked/" + model + "_mask"));
        }

        /// <summary>Soft round dot used by particles.</summary>
        public static Texture2D SoftDot
        {
            get
            {
                if (cache.TryGetValue("__dot", out var t) && t != null) return t;
                const int N = 64;
                t = new Texture2D(N, N, TextureFormat.RGBA32, false) { name = "softdot", wrapMode = TextureWrapMode.Clamp };
                var px = new Color32[N * N];
                for (int y = 0; y < N; y++)
                    for (int x = 0; x < N; x++)
                    {
                        float dx = (x + 0.5f) / N * 2 - 1, dy = (y + 0.5f) / N * 2 - 1;
                        float d = Mathf.Sqrt(dx * dx + dy * dy);
                        float a = Mathf.Clamp01(1 - d);
                        a = a * a * (3 - 2 * a);
                        px[y * N + x] = new Color32(255, 255, 255, (byte)(a * 255));
                    }
                t.SetPixels32(px);
                t.Apply();
                cache["__dot"] = t;
                return t;
            }
        }

        /// <summary>Grid texture for the box's back wall: one cell per tile, faint dashed lines.</summary>
        public static Texture2D GridCell
        {
            get
            {
                if (cache.TryGetValue("__grid", out var t) && t != null) return t;
                const int N = 128;
                t = new Texture2D(N, N, TextureFormat.RGBA32, true) { name = "gridcell", wrapMode = TextureWrapMode.Repeat, anisoLevel = 4 };
                var px = new Color32[N * N];
                for (int y = 0; y < N; y++)
                    for (int x = 0; x < N; x++)
                    {
                        int ex = Mathf.Min(x, N - 1 - x), ey = Mathf.Min(y, N - 1 - y);
                        bool line = ex < 2 || ey < 2;
                        bool dash = ((x / 8) % 2 == 0 && ey < 2) || ((y / 8) % 2 == 0 && ex < 2);
                        byte a = (byte)(line ? (dash ? 150 : 40) : 0);
                        px[y * N + x] = new Color32(255, 255, 255, a);
                    }
                t.SetPixels32(px);
                t.Apply();
                cache["__grid"] = t;
                return t;
            }
        }
    }
}
